---
# #####################################################################
# Deploy Helm
# #####################################################################
- name: DEPRECATION WARNING
  debug:
    msg: moving to separate role

- name: Helm download sources
  get_url:
    url: "{{ helm_url }}{{ helm_archive }}"
    dest: /tmp

- name: Helm extract into /tmp
  unarchive:
    src: /tmp/{{ helm_archive }}
    dest: /tmp
    remote_src: yes

- name: Helm copy binary to /usr/local/bin
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    remote_src: yes
    owner: root
    group: root
    mode: 0755

- name: Helm add repo
  become: true
  become_user: ubuntu
  command: helm repo add stable https://kubernetes-charts.storage.googleapis.com/

- name: Helm repo update
  become: true
  become_user: ubuntu
  command: helm repo update

- name: Helm bash command completion
  become: true
  become_user: ubuntu
  lineinfile:
    path: /home/ubuntu/.bashrc
    insertafter: EOF
    line: 'source <(helm completion bash)'
