---
# #####################################################################
# Create a Kubernetes master with kubeadm
# #####################################################################
#
# Preparations
#
- name: Create Proxy Configuration and Certificate for the Dashboard
  include_role:
    name: proxy
  vars:
    operation: create_site
    service_name: dashboard
    jumphost_external_ip: "{{ inventory_hostname }}"
    proxy_destination: "{{ k8smaster_ip }}"
    node_port: "{{ kubernetes_dashboard_nodeport }}"
    target_type: https
  when:
    - site_deploy_jumphost == True

- name: Deploy Golang
  include: deploy_golang.yml
  when:
    - deploy_golang == True
    - deploy_kubernetes == True

- name: Deploy Runc
  include: deploy_runc.yml
  when:
    - deploy_runc == True
    - deploy_kubernetes == True

- name: Deploy cni
  include: deploy_cni.yml
  when:
    - deploy_cni == True
    - deploy_kubernetes == True

- name: Deploy Docker
  include: deploy_docker.yml
  when:
    - deploy_docker == True
    - deploy_kubernetes == True

- name: Deploy Cri-O
  include: deploy_crio.yml
  when:
    - deploy_crio == True
    - deploy_kubernetes == True

- name: Deploy Kubernetes
  block:
    - include: deploy_kubernetes.yml

    #
    # Initialize cluster
    #
    - name: Kubeadm Pull Images
      command: >
        kubeadm config images pull
        --cri-socket={{ kubeadm_container_runtime_socket }}

    - name: Kubeadm Init
      shell: kubeadm init --apiserver-advertise-address="{{ apiserver_advertise_address }}" --apiserver-cert-extra-sans="{{ apiserver_cert_extra_sans }}" --pod-network-cidr="{{ pod_network_cidr }}" --cri-socket="{{ kubeadm_container_runtime_socket }}" >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: Kubernetes Setup Kubeconfig for Ubuntu User Make Directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Kubernetes Setup Kubeconfig for Ubuntu User Copy Config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '0600'
        remote_src: yes

    - name: Store Kubernetes Certificate to kubecfg.crt
      become: true
      become_user: ubuntu
      shell: grep 'client-certificate-data' /home/ubuntu/.kube/config | head -n 1 | awk '{print $2}' | base64 -d > kubecfg.crt
      args:
        chdir: $HOME
        creates: kubecfg.crt

    - name: Fetch kubecfg.crt
      become: true
      become_user: ubuntu
      fetch:
        src: /home/ubuntu/kubecfg.crt
        dest: ./site_{{ type }}/
        flat: yes

    - name: Store Kubernetes Key to kubecfg.key
      become: true
      become_user: ubuntu
      shell: grep 'client-key-data' /home/ubuntu/.kube/config | head -n 1 | awk '{print $2}' | base64 -d > kubecfg.key
      args:
        chdir: $HOME
        creates: kubecfg.key

    - name: Fetch kubecfg.key
      become: true
      become_user: ubuntu
      fetch:
        src: /home/ubuntu/kubecfg.key
        dest: ./site_{{ type }}/
        flat: yes

    - name: Create Kubernetes pkcs12
      become: true
      become_user: ubuntu
      shell: openssl pkcs12 -export -clcerts -inkey kubecfg.key -in kubecfg.crt -out kubecfg.p12 -name "kubernetes-client" -passout pass:trendmicro
      args:
        chdir: $HOME
        creates: kubecfg.p12

    - name: Fetch kubecfg.p12
      become: true
      become_user: ubuntu
      fetch:
        src: /home/ubuntu/kubecfg.p12
        dest: ./site_{{ type }}/
        flat: yes

    #
    # Create admin user
    #
    - name: Create admin-user Service Account
      become: true
      become_user: ubuntu
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: admin-user
            namespace: kube-system

    - name: Create admin-user ClusterRoleBinding
      become: true
      become_user: ubuntu
      k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: admin-user
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
            - kind: ServiceAccount
              name: admin-user
              namespace: kube-system

    - name: Query Kubernetes Secrets
      become: true
      become_user: ubuntu
      k8s_info:
        api_version: v1
        kind: secret
        namespace: kube-system
      register: k8ssecrets

    - name: Search admin-user-token
      set_fact:
        admintoken: "{% for resource in k8ssecrets.resources %}\
                       {% if 'admin-user-token' in resource.metadata.name %}\
                         {{ resource.data.token }}\
                       {% endif %}\
                     {% endfor %}"

    - name: Create Link Document for Kubernetes Admin Token
      become: true
      become_user: ubuntu
      copy:
        dest: /home/ubuntu/kubernetes-admin-token.txt
        mode: 0640
        content: |
          Token: {{ admintoken | b64decode }}

    - name: Fetch kubernetes-admin-token.txt
      become: true
      become_user: ubuntu
      fetch:
        src: /home/ubuntu/kubernetes-admin-token.txt
        dest: ./site_{{ type }}/
        flat: yes

    #
    # Create join command
    #
    # kubeadm token create has a bug and currently does not understand --cri-socket
    # Therefore we need to create a config file for kubeadm
    - name: Kubeadm Create Token Create Configuration File
      copy:
        dest: /root/kubeadm_token_create_config.yaml
        mode: 0640
        content: |
          apiVersion: kubeadm.k8s.io/v1beta1
          kind: InitConfiguration
          nodeRegistration:
            criSocket: "{{ kubeadm_container_runtime_socket }}"

    - name: Kubeadm Generate Join Command
      command: kubeadm token create --print-join-command --config=/root/kubeadm_token_create_config.yaml
      register: join_command

    - name: Kubeadm Copy Join Command to Local File
      become: true
      become_user: ansible
      local_action: copy content="{{ join_command.stdout_lines[0] }} --cri-socket={{ kubelet_container_runtime_socket }}" dest="./site_{{ type }}/join-command"

    - name: Kubernetes Bash Command Completion
      become: true
      become_user: ubuntu
      lineinfile:
        path: /home/ubuntu/.bashrc
        insertafter: EOF
        line: 'source <(kubectl completion bash)'

    - name: Fun with Kubectl Aliases - Generate Aliases
      script: generate_aliases.py
      args:
        executable: python3
      register: aliases
      delegate_to: localhost

    - name: Fun with Kubectl Aliases - Create Aliases File
      become: true
      become_user: ubuntu
      copy:
        dest: /home/ubuntu/.kubectl_aliases
        mode: 0640
        owner: ubuntu
        content: "{{ aliases.stdout }}"

    - name: Fun with Kubectl Aliases - Append Aliaes to .bashrc
      become: yes
      become_user: ubuntu
      lineinfile:
        path: $HOME/.bashrc
        insertafter: EOF
        line: "{{ item }}"
      loop:
        - '[ -f ~/.kubectl_aliases ] && source ~/.kubectl_aliases'
        - 'function kubectl() { echo "+ kubectl $@">&2; command kubectl $@; }'

    - name: Copy stern
      copy:
        src: ./files/stern
        dest: /usr/local/bin/stern
        mode: 0755
  when: deploy_kubernetes == True

- name: Deploy Pod Network
  include: deploy_pod_network.yml
  when:
    - deploy_pod_network == True
    - deploy_kubernetes == True

- name: Deploy Kubernetes Dashboard
  include: deploy_kubernetes_dashboard.yml
  when: deploy_kubernetes == True
