# #####################################################################
# Create and Manage PostgreSQL
# #####################################################################
---
- name: Deploy
  include: deploy.yml
  when: operation == 'deploy'

- name: Create database
  include: create_database.yml
  when: operation == 'create_database'
