# #####################################################################
# Create and Manage PostgreSQL
# #####################################################################
---
- name: Create instance
  include: psql_create_instance.yml
  when: operation == 'create_instance'

- name: Create database
  include: psql_create_database.yml
  when: operation == 'create_database'
