---
# #####################################################################
# Create a GitLab
# #####################################################################
- name: Generate DNS Name for GitLab
  set_fact:
    service_dns_name: "https://gitlab-{{ hostvars[inventory_hostname]['groups']['tag_role_jumphost'][0] | regex_replace('\\.', '-') }}.{{ jumphost_tld }}"

- name: Create GitLab Overrides File
  copy:
    dest: /home/ubuntu/overrides-gitlab-metallb.yml
    mode: 0640
    owner: ubuntu
    content: |
      global:
        edition: ce
        ingress:
          configureCertmanager: false
        hosts:
          domain: {{ hostvars[inventory_hostname]['groups']['tag_role_k8sworker'][0] }}.{{ jumphost_tld }}
          externalIP: {{ hostvars[inventory_hostname]['groups']['tag_role_k8sworker'][0] }}
      certmanager:
        install: false
      gitlab-runner:
        install: true

- name: Install GitLab Repo
  become: true
  become_user: ubuntu
  shell: helm repo add gitlab https://charts.gitlab.io/

- name: Update GitLab Repo
  become: true
  become_user: ubuntu
  shell: helm repo update

- name: Create GitLab Namespace
  become: true
  become_user: ubuntu
  shell: kubectl create namespace {{ gitlab_namespace }} --dry-run=true -o yaml | kubectl apply -f -
  args:
    chdir: $HOME

- name: Install GitLab
  become: true
  become_user: ubuntu
  shell: helm install --namespace {{ gitlab_namespace }} --values overrides-gitlab-metallb.yml {{ gitlab_name }} {{ gitlab_chart }} >> gitlab.log
  args:
    chdir: $HOME
    creates: gitlab.log

# - name: Create GitLab Rails Secret
#   become: true
#   become_user: ubuntu
#   shell: |
#     cat << EOF > /home/ubuntu/gitlab-rails-secret.yml
#     production:
#       secret_key_base: $(head -c 512 /dev/urandom | LC_CTYPE=C tr -cd 'a-zA-Z0-9' | head -c 128)
#       otp_key_base: $(head -c 512 /dev/urandom | LC_CTYPE=C tr -cd 'a-zA-Z0-9' | head -c 128)
#       db_key_base: $(head -c 512 /dev/urandom | LC_CTYPE=C tr -cd 'a-zA-Z0-9' | head -c 128)
#       openid_connect_signing_key: |
#       $(openssl genrsa 2048 | awk '{print "    " $0}')
#     EOF
#   args:
#     chdir: $HOME
#     creates: gitlab-rails-secret.yml

# - name: Create GitLab Rails Secret
#   become: true
#   become_user: ubuntu
#   shell: kubectl -n gitlab create secret generic {{ gitlab_name }}-rails-secret --from-file=/home/ubuntu/gitlab-rails-secret.yml > gitlab-rails-secret-created.txt
#   args:
#     chdir: $HOME
#     creates: gitlab-rails-secret-created.txt

# - name: GitLab patch http port
#   become: true
#   become_user: ubuntu
#   command: kubectl patch service -n {{ gitlab_namespace }} gitlab-nginx-ingress-controller --type='json' --patch='[{"op":"replace", "path":"/spec/ports/0/nodePort", "value":{{ gitlab_nodeport_http }}}]'

- name: GitLab patch https port
  become: true
  become_user: ubuntu
  command: kubectl patch service -n {{ gitlab_namespace }} gitlab-nginx-ingress-controller --type='json' --patch='[{"op":"replace", "path":"/spec/ports/1/nodePort", "value":{{ gitlab_nodeport_https }}}]'
  ignore_errors: yes

# - name: GitLab patch ssh port
#   become: true
#   become_user: ubuntu
#   command: kubectl patch service -n {{ gitlab_namespace }} gitlab-nginx-ingress-controller --type='json' --patch='[{"op":"replace", "path":"/spec/ports/2/nodePort", "value":{{ gitlab_nodeport_ssh }}}]'

- name: Fetch gitlab.log
  become: true
  become_user: ubuntu
  fetch:
    src: /home/ubuntu/gitlab.log
    dest: ./site_{{ type }}/
    flat: yes

- name: Query root Password
  become: true
  become_user: ubuntu
  shell: kubectl get --namespace {{ gitlab_namespace }} secret gitlab-gitlab-initial-root-password -ojsonpath='{.data.password}' | base64 --decode
  register: root_password

- name: Create link document for GitLab
  become: true
  become_user: ubuntu
  copy:
    dest: /home/ubuntu/gitlab.txt
    mode: 0640
    content: |
      echo URL: http://{{ inventory_hostname }}:{{ gitlab_nodeport_https }}
      URL: {{ service_dns_name }}
      echo Username: root
      echo Password: {{ root_password.stdout }}

- name: Fetch gitlab.txt
  become: true
  become_user: ubuntu
  fetch:
    src: /home/ubuntu/gitlab.txt
    dest: ./site_{{ type }}/
    flat: yes
