# #####################################################################
# Create and Manage GitLab
# #####################################################################
---
- name: Create instance
  include: gitlab_create_instance.yml
  when: operation == 'create_instance'

- name: Create instance
  include: gitlab_create_instance_docker.yml
  when: operation == 'create_instance_docker'
