# #####################################################################
# Create and Manage GitLab
# #####################################################################
---
- name: Deploy
  include: deploy.yml
  when: operation == 'deploy'

- name: Deploy Runners
  include: deploy_runners.yml
  when: operation == 'deploy_runners'
