# #####################################################################
# Create, Manage and Terminate the Cluster Registry
# #####################################################################
---
- name: Deploy
  include: deploy.yml
  when: operation == 'deploy'
