# #####################################################################
# Create and Manage Linkerd
# #####################################################################
---
- name: Create instance
  include: linkerd_create_instance.yml
  when: operation == 'create_instance'
