# #####################################################################
# Create and Manage Grafana
# #####################################################################
---
- name: Deploy
  include: deploy.yml
  when: operation == 'deploy'
