# #####################################################################
# Create, Manage and Terminate Azure environment
# #####################################################################
---
- name: Create network and firewall rules
  include: azure_create_network.yml
  when: operation == 'create_network'

- name: Create linux instance
  include: azure_create_linux_instance.yml
  when: operation == 'create_linux_instance'

- name: Terminate instance
  include: azure_terminate_instance.yml
  when: operation == 'terminate_instance'

- name: Terminate network
  include: azure_terminate_network.yml
  when: operation == 'terminate_network'

  # - name: Create some instances
  #   include: gcp_create_instances.yml
  #   when: operation == 'create_instances'
