# #####################################################################
# Create and Manage Deep Security
# #####################################################################
---
- name: Deploy
  include: deploy.yml
  when: operation == 'deploy'

- name: Fetch System Configuration
  include: fetch_system_configuration.yml
  when: operation == 'fetch_system_configuration'

- name: Copy System Configuration
  include: copy_system_configuration.yml
  when: operation == 'copy_system_configuration'
