---
# #####################################################################
# Deploy Deep Security Smart Check
# #####################################################################

# #####################################################################
# Query some private ips
# #####################################################################
- hosts: tag_role_jumphost
  tasks:
    - name: Get ipaddr of Jumphost
      set_fact:
        remote_ip: "{{ inventory_hostname | ipaddr}}"

    - name: Get ipaddr of Jumphost
      set_fact:
        remote_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      when: not remote_ip

    - name: Store external ip address of Jumphost
      add_host:
        name: "{{ remote_ip }}"
        groups: "moadsd_ng_jumphost_instance_public"

- hosts: localhost
  gather_facts: false
  tasks:
    - name: Include vars
      include: site_vars.yml
    
    - name: Listing Jumphost Environment
      debug:
        msg:
          - "Jumphost                     : {{ jumphost_ip }}"
      when: site_deploy_jumphost == True

    - name: Listing Kubernetes Environment
      debug:
        msg:
          - "Kubernetes Master            : {{ k8smaster_ip }}"
          - "Kubernetes Worker 1          : {{ k8sworker1_ip }}"
      when: site_deploy_kubernetes == True

    - name: Listing OpenShift Environment
      debug:
        msg:
          - "OpenShift Master             : {{ openshift_ip }}"
      when: site_deploy_openshift == True

    - name: Listing Deep Security Environment
      debug:
        msg:
          - "Deep Security                : {{ dsm_ip }}"
          - "PostgreSQL                   : {{ dsmdb_ip }}"
      when:
        - site_deploy_deepsecurity == True
        - deepsecurity_variant == 'dsm'

# #####################################################################
# Deploy Deep Security Smart Check
# #####################################################################
- name: Deploy Deep Security Smart Check
  hosts: tag_role_k8smaster
  become: true

  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Deploy Deep Security Smart Check
      include_role:
        name: smartcheck
      vars:
        operation: deploy
        activationCode: "{{ smartcheck_license }}"
        auth_masterPassword: trendmicro

    - name: Configure Deep Security Smart Check
      include_role:
        name: smartcheck
      vars:
        operation: configure
