---
# #####################################################################
# Deploy Endpoints / Servers
# #####################################################################

# #####################################################################
# Query some private ips
# #####################################################################
- hosts: tag_role_jumphost
  tasks:
    - name: Get ipaddr of Jumphost
      set_fact:
        remote_ip: "{{ inventory_hostname | ipaddr}}"

    - name: Get ipaddr of Jumphost
      set_fact:
        remote_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      when: not remote_ip

    - name: Store external ip address of Jumphost
      add_host:
        name: "{{ remote_ip }}"
        groups: "moadsd_ng_jumphost_instance_public"

    - name: Store all Groups in Memory
      set_fact:
        moadsd_ng_groups: "{{ hostvars[inventory_hostname]['groups'] }}"

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Listing Jumphost Environment
      debug:
        msg:
          - "Jumphost                     : {{ hostvars[inventory_hostname]['groups']['tag_role_jumphost'][0] }}"
      when: site_deploy_jumphost == True

    - name: Listing Kubernetes Environment
      debug:
        msg:
          - "Kubernetes Master            : {{ hostvars[inventory_hostname]['groups']['tag_role_k8smaster'][0] }}"
          - "Kubernetes Worker 1          : {{ hostvars[inventory_hostname]['groups']['tag_role_k8sworker'][0] }}"
      when: "'tag_role_k8smaster' is in groups"

    - name: Listing OpenShift Environment
      debug:
        msg:
          - "OpenShift Master             : {{ hostvars[inventory_hostname]['groups']['tag_role_openshift'][0] }}"
      when: "'tag_role_openshift' is in groups"

    - name: Listing Deep Security Environment
      debug:
        msg:
          - "Deep Security                : {{ hostvars[inventory_hostname]['groups']['tag_role_dsm'][0] }}"
          - "PostgreSQL                   : {{ hostvars[inventory_hostname]['groups']['tag_role_dsm_db'][0] }}"
      when: "'tag_role_dsm' is in groups"

# #####################################################################
# Deploy Endpoints / Servers
# #####################################################################
- name: Deploy Endpoints
  hosts: tag_role_linuxep, tag_role_windowsep

  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Deploy DSA with DSaaS
      include_role:
        name: deepsecurity-agent
      vars:
        operation: deploy
        tenant_id: "{{ deepsecurity_tenant_id }}"
        tenant_password: "{{ deepsecurity_administrator_password }}"
        token: "{{ deepsecurity_token }}"
        force_reactivation: False
      when:
        # - site_deploy_endpoints == True
        - deepsecurity_variant == 'dsaas'

    - name: Deploy DSA with DSM on MOADSD-NG
      include_role:
        name: deepsecurity-agent
      vars:
        operation: deploy
        dsm_agent_download_hostname: "{{ hostvars[inventory_hostname]['groups']['tag_role_dsm'][0] }}"
        dsm_agent_download_port: 4119
        dsm_agent_activation_hostname: "{{ hostvars[inventory_hostname]['groups']['tag_role_dsm'][0] }}"
        dsm_agent_activation_port: 4120
        force_reactivation: False
      when:
        # - site_deploy_endpoints == True
        - deepsecurity_variant == 'dsm'

- name: Set Linux Server policy
  hosts: tag_role_linuxep
  tasks:
    - name: Set Policy
      include_role:
        name: deepsecurity-agent
      vars:
        operation: set-policy-by-name
        policy_name: Linux Server

- name: Set Windows Server policy
  hosts: tag_role_windowsep
  tasks:
    - name: Set Policy
      include_role:
        name: deepsecurity-agent
      vars:
        operation: set-policy-by-name
        policy_name: Windows Server

- name: Update Configuration
  hosts: tag_role_linuxep, tag_role_windowsep
  tasks:
    - name: Update Configuration
      include_role:
        name: deepsecurity-agent
      vars:
        operation: update-configuration
    - name: Initiate Recommendation Scan
      include_role:
        name: deepsecurity-agent
      vars:
        operation: run-recommendation-scans

- name: Prepare Facter for Deep Security
  hosts: tag_role_linuxep
  become: yes
  tasks:
    - name: Update APT cache
      yum:
        update_cache: yes
    - name: Install the latest version of "facter"
      yum:
        name: facter
        state: present
    - name: "Create custom fact directory"
      file:
        path: "/etc/ansible/facts.d"
        state: "directory"
    - name: "Insert custom fact file"
      copy:
        src: ./files/dsa_status.fact
        dest: /etc/ansible/facts.d/dsa_status.fact
        mode: 0755
