---
# #####################################################################
# Deploy MOADSD-NG Environment
# #####################################################################

# #####################################################################
# Store some private ips within the ansible hostvars
# #####################################################################
- hosts: tag_role_jumphost
  tasks:
    - name: Get ipaddr of jumphost
      set_fact:
        remote_ip: "{{ inventory_hostname | ipaddr}}"

    - name: Get ipaddr of jumphost
      set_fact:
        remote_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      when: not remote_ip

    - name: Store external ip address of jumphost
      add_host:
        name: "{{ remote_ip }}"
        groups: "moadsd_ng_jumphost_instance_public"

- hosts: tag_role_k8smaster
  tasks:
    - name: Get internal ip address of kubernetes master
      add_host:
        name: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        groups: "moadsd_ng_k8smaster_instance"

- hosts: tag_role_dsm
  tasks:
    - name: Get internal ip address of deep security
      add_host:
        name: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        groups: "moadsd_ng_dsm_instance"

- hosts: tag_role_dsm_db
  tasks:
    - name: Get internal ip address of postgresql
      add_host:
        name: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        groups: "moadsd_ng_postgresql_instance"

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Listing environment
      debug:
        msg:
          - "Jumphost                     : {{ groups['moadsd_ng_jumphost_instance_public'][0] }}"
      when: site_deploy_jumphost == True

    - name: Listing environment
      debug:
        msg:
          - "Kubernetes Master            : {{ groups['moadsd_ng_k8smaster_instance'][0] }}"
      when: site_deploy_kubernetes == True

    - name: Listing environment
      debug:
        msg:
          - "Deep Security                : {{ groups['moadsd_ng_dsm_instance'][0] }}"
          - "PostgreSQL                   : {{ groups['moadsd_ng_postgresql_instance'][0] }}"
      when: site_deploy_deepsecurity == True

# #####################################################################
# Deploy GitLab
# #####################################################################
- name: Deploy GitLab
  hosts: tag_role_k8smaster
  become: true

  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Purge GitLab
      become: true
      become_user: ubuntu
      shell: helm delete --purge gitlab
      args:
        chdir: $HOME
      ignore_errors: yes

    - name: Delete gitlab.*
      become: true
      become_user: ubuntu
      file:
        state: absent
        path: "{{ item }}"
      loop:
        - ~/gitlab.txt
        - ~/gitlab.log

    - name: Deploy GitLab
      include_role:
        name: gitlab
      vars:
        operation: create_instance
      when: site_deploy_gitlab == True
