- hosts: tag_role_jumphost
  gather_facts: false
  tasks:
    - name: Get ipaddr of jumphost
      set_fact:
        remote_ip: "{{ inventory_hostname | ipaddr}}"

    - name: Get ipaddr of jumphost
      set_fact:
        remote_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      when: not remote_ip

    - name: Store external ip address of jumphost
      add_host:
        name: "{{ remote_ip }}"
        groups: "moadsd_ng_jumphost_instance_public"

- hosts: tag_role_k8smaster
  vars:
  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Create Jenkins Credentials
      include_role:
        name: jenkins
      vars:
        operation: create_credentials
      when: site_deploy_jenkins == True

# #####################################################################
# Patch Docker to allow insecure registries and docker.sock for all
# local users. Only when k8s runtime is docker.
# #####################################################################
- hosts: tag_role_k8smaster, tag_role_k8sworker
  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Change Docker Socket Permissions
      become: true
      file:
        path: /var/run/docker.sock
        mode: '666'

    - name: Docker restart
      become: true
      command: systemctl reload docker
