- hosts: tag_role_jumphost:&tag_user_{{ user }}
  gather_facts: false
  tasks:
    - name: Get ipaddr of jumphost
      set_fact:
        remote_ip: "{{ inventory_hostname | ipaddr}}"

    - name: Get ipaddr of jumphost
      set_fact:
        remote_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      when: not remote_ip

    - name: Store external ip address of jumphost
      add_host:
        name: "{{ remote_ip }}"
        groups: "moadsd_ng_jumphost_instance_public"

- hosts: tag_role_k8smaster:&tag_user_{{ user }}
  vars:
  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Create Jenkins Credentials
      include_role:
        name: jenkins
      vars:
        operation: create_credentials
      when: site_deploy_jenkins == True
