---
# #####################################################################
# Pause MOADSD-NG Environment in AWS
# #####################################################################
- name: Pause MOADSD-NG Environment
  hosts: localhost
  gather_facts: no
  connection: local
  vars:

  tasks:
    - name: Check if AWS cloud SDK is installed
      command: aws --version
      register: aws_installed
      changed_when: false
      ignore_errors: yes
    
    - fail:
        msg: "Please make sure AWS Cloud SDK is installed before executing the role."
      when: aws_installed is failed
    
    - name: Include vars
      include: site_vars.yml
      
    - name: Pause instance of Kubernetes master
      include_role:
        name: environment-aws
      vars:
        operation: pause_instance
        instance_name: "{{ kubernetes_master_instance_name }}"
    
    - name: Pause instance of Kubernetes worker(s)
      include_role:
        name: environment-aws
      vars:
        operation: pause_instance
        instance_name: "{{ kubernetes_worker_instance_name }}{{ item }}"
      with_sequence: count="{{ kubernetes_worker_count }}"
    
    - name: Pause instance of PostgreSQL
      include_role:
        name: environment-aws
      vars:
        operation: pause_instance
        instance_name: "{{ postgresql_instance_name }}"
    
    - name: Pause instance of Deep Security Manager
      include_role:
        name: environment-aws
      vars:
        operation: pause_instance
        instance_name: "{{ deepsecurity_instance_name }}"
    
    - name: Pause linux endpoint instances
      include_role:
        name: environment-aws
      vars:
        operation: pause_instance
        instance_name: "{{ linuxep_instance_name }}{{ item }}"
      with_sequence: count="{{ linuxep_instance_count }}"
    
    - name: Pause windows endpoint instances
      include_role:
        name: environment-aws
      vars:
        operation: pause_instance
        instance_name: "{{ windowsep_instance_name }}{{ item }}"
      with_sequence: count="{{ windowsep_instance_count }}"
    
    - name: Pause jumphost
      include_role:
        name: environment-aws
      vars:
        operation: pause_instance
        instance_name: "{{ jumphost_instance_name }}"
