---
# #####################################################################
# Switches the MOADSD-NG Environment to ESXi
# #####################################################################
- name: Switches the MOADSD-NG Environment to ESXi
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Find yml files in group_vars
      find:
        paths: "./group_vars"
        patterns: "*.yml"
      register: files_to_delete

    - name: Delete yml files in group_vars
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"
