---
# #####################################################################
# Create a windows instance in GCP environment
# #####################################################################
- name: Current play
  debug:
    msg: "Creating instance {{ moadsd_ng_prefix }}-{{ instance_name }}-instance"

- name: Ensure the project network is created
  include: gcp_create_network.yml

- name: Create a firewall opening ports for anywhere
  gcp_compute_firewall:
    name: "{{ moadsd_ng_prefix }}-{{ instance_name }}-anywhere-firewall"
    network:
      selfLink: "global/networks/{{ network.name }}"
    allowed:
      - ip_protocol: tcp
        ports: "{{ instance_ports_anywhere }}"
      - ip_protocol: udp
        ports: "{{ instance_ports_anywhere }}"
      - ip_protocol: icmp
    target_tags:
      - "{{ instance_tags }}"
    source_ranges: ['0.0.0.0/0']
    project: "{{ gcp_project_id }}"
    priority: 1000
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
    scopes: "{{ scopes }}"
    state: present
  register: firewall

- name: Create a firewall opening ports for internal network
  gcp_compute_firewall:
    name: "{{ moadsd_ng_prefix }}-{{ instance_name }}-firewall"
    network:
      selfLink: "global/networks/{{ network.name }}"
    allowed:
      - ip_protocol: tcp
        ports: "{{ instance_ports_network }}"
      - ip_protocol: udp
        ports: "{{ instance_ports_network }}"
      - ip_protocol: icmp
    target_tags:
      - "{{ instance_tags }}"
    source_tags:
      - "{{ gcp_project_id }}"
    project: "{{ gcp_project_id }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
    scopes: "{{ scopes }}"
    state: present
  register: firewall

- name: Create a disk for windows server
  gcp_compute_disk:
    name: "{{ moadsd_ng_prefix }}-{{ instance_name }}-disk"
    size_gb: "{{ instance_size_gb }}"
    source_image: "{{ instance_source_image }}"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project_id }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
    scopes: "{{ scopes }}"
    state: present
  register: disk

- name: Create a windows server public address
  gcp_compute_address:
    name: "{{ moadsd_ng_prefix }}-{{ instance_name }}-address"
    region: "{{ gcp_region }}"
    project: "{{ gcp_project_id }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
    scopes: "{{ scopes }}"
    state: present
  register: address
  when:
    - instance_public_address == False

- name: Create GCP public instance
  block:
    - name: Create a windows instance
      gcp_compute_instance:
        state: present
        name: "{{ moadsd_ng_prefix }}-{{ instance_name }}-instance"
        machine_type: "{{ instance_machine_type }}"
        deletion_protection: no
        disks:
          - auto_delete: true
            boot: true
            source: "{{ disk }}"
        metadata:
          sysprep-specialize-script-ps1: "{{ instance_startup_script }}"
        network_interfaces:
          - network:
              selfLink: "global/networks/{{ network.name }}"
            access_configs:
              - name: 'External NAT'
                nat_ip: "{{ address }}"
                type: 'ONE_TO_ONE_NAT'
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project_id }}"
        tags:
          items:
            - windows
            - "{{ gcp_project_id }}"
            - "{{ instance_tags }}"
            - "project-{{ moadsd_ng_prefix }}"
            - "user-{{ moadsd_ng_user }}"
        auth_kind: "{{ gcp_auth_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        scopes: "{{ scopes }}"
      register: instance

    - name: Create admin password
      delegate_to: 127.0.0.1
      command: gcloud beta compute --project "{{ gcp_project_id }}" reset-windows-password "{{ moadsd_ng_prefix }}-{{ instance_name }}-instance" --zone "{{ gcp_zone }}" --quiet
      retries: 10
      delay: 5
      register: username_password
      until: username_password.rc == 0

    - name: Configure group_vars for windows instance
      delegate_to: 127.0.0.1
      copy:
        dest: "./host_vars/{{ instance.networkInterfaces[0].accessConfigs[0].natIP }}.yml"
        content: |
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_password: '{{ username_password.stdout_lines[1] | regex_replace('password:   ') }}'
          ansible_user: '{{ username_password.stdout_lines[2] | regex_replace('username:   ') }}'
        force: yes

  when:
    - instance_public_address == True

- name: Create GCP private instance
  block:
    - name: Create a windows instance
      gcp_compute_instance:
        state: present
        name: "{{ moadsd_ng_prefix }}-{{ instance_name }}-instance"
        machine_type: "{{ instance_machine_type }}"
        deletion_protection: no
        disks:
          - auto_delete: true
            boot: true
            source: "{{ disk }}"
        metadata:
          sysprep-specialize-script-ps1: "{{ instance_startup_script }}"
        network_interfaces:
          - network:
              selfLink: "global/networks/{{ network.name }}"
            access_configs:
              - name: 'External NAT'
                type: 'ONE_TO_ONE_NAT'
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project_id }}"
        tags:
          items:
            - windows
            - "{{ gcp_project_id }}"
            - "{{ instance_tags }}"
            - "project-{{ moadsd_ng_prefix }}"
            - "user-{{ moadsd_ng_user }}"
        auth_kind: "{{ gcp_auth_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        scopes: "{{ scopes }}"
      register: instance

  when:
    - instance_public_address == False
