# #####################################################################
# Create and Manage the MOADSD-NG Proxy
# #####################################################################
---
- name: Deploy
  include: deploy.yml
  when: operation == 'deploy'

- name: Create Site Config
  include: create_site.yml
  when: operation == 'create_site'
