---
# #####################################################################
# Create a Reverse Proxy for MOADSD-NG Services
# #####################################################################
- name: Certbot add apt repository
  apt_repository:
    repo: ppa:certbot/certbot
    state: present

- name: Install Packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - nginx
      - software-properties-common
      - python-certbot-nginx

- name: Remove default nginx config
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent
