---
# #####################################################################
# Create a Site Config for a MOADSD-NG Service
# #####################################################################
- name: Generate DNS name
  set_fact:
    service_dns_name: "{{ service_name }}-{{ jumphost_external_ip | regex_replace('\\.', '-') }}.nip.io"

- name: Creating Site Config
  debug:
    msg: "{{ service_dns_name }}"

- name: Nginx stop
  service:
    name: nginx
    state: stopped

- name: Install nginx site for http site
  template:
    src: nginx_http_proxy.j2
    dest: /etc/nginx/sites-enabled/http-{{ service_name }}.conf
  when: target_type == "http"

- name: Install https site
  block:
    - name: Install nginx site for https site
      template:
        src: nginx_https_proxy.j2
        dest: /etc/nginx/sites-enabled/https-{{ service_name }}.conf

    - name: Request Certificate from Staging Certification Authority
      command: >-
        certbot --test-cert --noninteractive --agree-tos
        --email {{ admin_email }} {{ certbot_create_method }}
        -d {{ service_dns_name }}
      when: trusted_certificates == False

    - name: Request Certificate from Production Certification Authority
      command: >-
        certbot --noninteractive --agree-tos
        --email {{ admin_email }} {{ certbot_create_method }}
        -d {{ service_dns_name }}
      when: trusted_certificates == True
  when: target_type == "https"

- name: Nginx restart
  service:
    name: nginx
    daemon_reload: yes
    state: restarted
