---
# #####################################################################
# Create a Site Config for a MOADSD-NG Service
# #####################################################################
- name: debug
  debug:
    msg: "{{ service_name }}.{{ jumphost_external_ip | regex_replace('\\.', '-') }}.nip.io"

- name: Generate DNS name
  set_fact:
    service_dns_name: "{{ service_name }}.{{ jumphost_external_ip | regex_replace('\\.', '-') }}.nip.io"

- name: Debug
  debug:
    msg: "{{ service_dns_name }}"

- name: Install nginx site for http site
  template:
    src: nginx_http_proxy.j2
    dest: /etc/nginx/sites-enabled/http-{{ service_name }}
  when: target_type == "http"

- name: Install https site
  block:
    - name: Install nginx site for https site
      template:
        src: nginx_https_proxy.j2
        dest: /etc/nginx/sites-enabled/https-{{ service_name }}.conf

    - name: Request Certificate
      command: >-
        certbot --test-cert --noninteractive --agree-tos
        --email {{ certbot_admin_email }} --standalone certonly
        -d {{ service_dns_name }}
  when: target_type == "https"

- name: Nginx restart
  service:
    name: nginx
    daemon_reload: yes
    state: restarted
