---
# #####################################################################
# Create a Reverse Proxy for MOADSD-NG Services
# #####################################################################
- name: Certbot add apt repository
  apt_repository:
    repo: ppa:certbot/certbot
    state: present
  when: ansible_pkg_mgr == "apt"

- name: Install Packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - nginx
      - software-properties-common
      - python-certbot-nginx
  when: ansible_pkg_mgr == "apt"

- name: Install Packages
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - yum-utils
  when: ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "zypper"

- name: Yum Config Manager AWS
  command: yum-config-manager --enable rhui-{{ region }}-rhel-server-extras rhui-{{ region }}-rhel-server-optional
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "zypper"
    - type == "aws"

- name: Install Packages
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - certbot
      - python2-certbot-nginx
      - nginx
  when: ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "zypper"

- name: Remove default nginx config
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Nginx restart
  service:
    name: nginx
    daemon_reload: yes
    state: restarted
