# #####################################################################
# Create, Manage and Terminate MetalLB LoadBalancer
# #####################################################################
---
- name: Create instance
  include: metallb_create_instance.yml
  when: operation == 'create_instance'

- name: Configure Smart Check
  include: metallb_configure.yml
  when: operation == 'configure'
