# #####################################################################
# Create, Manage and Terminate MetalLB LoadBalancer
# #####################################################################
---
- name: Deploy
  include: deploy.yml
  when: operation == 'deploy'

- name: Configure
  include: configure.yml
  when: operation == 'configure'
