# #####################################################################
# Site Deploy Components
# #####################################################################
site_deploy_kubernetes: yes
site_deploy_openshift: no
site_deploy_deepsecurity: no
site_deploy_smartcheck: yes
site_deploy_jenkins: yes
site_deploy_rancher: yes
site_deploy_harbor: no
site_deploy_longhorn: no
site_deploy_gitlab: no
site_deploy_endpoints: no
site_deploy_linkerd: no
site_deploy_prometheus: yes
site_deploy_grafana: yes
site_deploy_opa: no
site_deploy_jumphost: yes

moadsd_ng_prefix: moadsd-ng
moadsd_ng_user: maygyver
instance_shutdown_delay: 240

# #####################################################################
# Google Cloud Settings
# #####################################################################
gcp_project_id: MANDATORY
gcp_region: europe-west2
gcp_zone: europe-west2-b
gcp_service_account_file: /home/ansible/ansible.json

# #####################################################################
# Google images
# #####################################################################
image_ubuntu: projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts
image_redhat: projects/rhel-cloud/global/images/family/rhel-8
image_windows: projects/windows-cloud/global/images/family/windows-2012-r2

# #####################################################################
# AWS Cloud Settings
# #####################################################################
aws_zone: eu-central-1a
aws_region: eu-central-1
aws_key_name: moadsd-ng
aws_pem: /home/ansible/.ssh/moadsd-ng

# #####################################################################
# AWS Images
# #####################################################################
ami_ubuntu: ami-0ac05733838eabc06
ami_redhat: ami-00e37cffd3bb3ac8d
ami_windows: ami-0cbf1b1038bbb408d

# #####################################################################
# AWS Credentials
# #####################################################################
aws_access_key: MANDATORY
aws_secret_key: MANDATORY

# #####################################################################
# ESX Credentials
# #####################################################################
kubernetes_master_login_user: k8s
kubernetes_master_login_password: trendmicro
kubernetes_worker_login_user: k8s
kubernetes_worker_login_password: trendmicro
kubernetes_master_instance_name: vk8smaster
kubernetes_worker_instance_name: vk8sworker

# #####################################################################
# Linux Jumphost Settings
# #####################################################################
jumphost_tld: nip.io

# #####################################################################
# Kubernetes Settings
# #####################################################################
kubernetes_container_runtime: docker
kubernetes_worker_count: 3
cluster_networking: flannel_flannel

# #####################################################################
# Deep Security Settings
# #####################################################################
deepsecurity_variant: dsaas

# #####################################################################
# Linux Endpoint Settings
# #####################################################################
linuxep_instance_count: 1

# #####################################################################
# Windows Endpoint Settings
# #####################################################################
windowsep_instance_count: 0

# #####################################################################
# Site Secrets
# #####################################################################
# Deep Security
deepsecurity_license: MANDATORY
deepsecurity_administrator_username: admin
deepsecurity_administrator_password: trendmicro
deepsecurity_database_password: trendmicro

# Deep Security as a Service
deepsecurity_tenant_id: MANDATORY
deepsecurity_token: MANDATORY

# Deep Security Smart Check
smartcheck_license: MANDATORY
smartcheck_username: admin
smartcheck_password: trendmicro
smartcheck_master_password: trendmicro
smartcheck_secret_seed: trendmicro
smartcheck_registry_username: reguser
smartcheck_registry_password: trendmicro
smartcheck_database_username: dssc
smartcheck_database_password: trendmicro
smartcheck_storageclass: rook-ceph-block

# Cloud One Application Security
application_security_key: OPTIONAL
application_security_secret: OPTIONAL

# CodeReady Containers
openshift_pull_secret: MANDATORY

# Jenkins
jenkins_username: admin
jenkins_password: trendmicro
jenkins_token: OPTIONAL
jenkins_github_access_token: OPTIONAL

# GitLab
gitlab_runner_registration_token: OPTIONAL

# Harbor
harbor_username: admin
harbor_password: trendmicro
harbor_secret_key: not-a-secure-key
harbor_registry_user: reguser
harbor_registry_password: trendmicro
# If you update the username or password of registry, make sure use cli tool htpasswd to generate the bcrypt hash
# e.g. "htpasswd -nbBC10 $username $password"
harbor_registry_htpasswd: "reguser:$2y$10$s23SJHWQgxiiDRDJM/EHbe/avGlQciQtHdDYtTum6NQCzgnwmMIOe"

# Rancher
rancher_username: admin
rancher_password: trendmicro

# Cluster Registry
cluster_registry_username: reguser
cluster_registry_password: trendmicro

# Grafana
# Only required, if you are using Grafana
grafana_username: admin
grafana_password: trendmicro

# Ansible
ansible_ssh_key: MANDATORY
admin_email: MANDATORY

# Docker Hub
dockerhub_username: OPTIONAL
dockerhub_password: OPTIONAL

# Github
github_username: OPTIONAL
github_password: OPTIONAL

# Trusted Certificates
trusted_certificates: False
