kubernetes_version: 1.17.2-00
kubernetes_dashboard_url: https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml

crio_version: release-1.17

docker_version: 5:18.09.8~3-0~ubuntu-xenial
# docker_version: 5:19.03.7~3-0~ubuntu-xenial
