---
# #####################################################################
# Terminate the network in AWS environment
# #####################################################################
- name: Current play
  debug:
    msg:
      - "Terminating network {{ moadsd_ng_prefix }}-vpc"

- name: Create an EC2 VPC
  ec2_vpc_net:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: "{{ moadsd_ng_prefix }}-vpc"
    cidr_block: "{{ aws_vpc_cidr_block }}"
    region: "{{ aws_region }}"
    dns_support: yes
    dns_hostnames: yes
    tenancy: default
    state: present
  register: ec2_vpc_net_result

- name: Create EC2 VPC Public Subnet within CIDR block
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ aws_region }}"
    az: "{{ aws_zone }}"
    state: present
    cidr: "{{ aws_public_subnet_cidr_block }}"
    map_public: yes
    resource_tags:
      Name: "{{ moadsd_ng_prefix }}-public-subnet"
  register: public_subnet_result

- name: Create EC2 VPC Private Subnet within CIDR block
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ aws_region }}"
    az: "{{ aws_zone }}"
    state: present
    cidr: "{{ aws_private_subnet_cidr_block }}"
    map_public: yes
    resource_tags:
      Name: "{{ moadsd_ng_prefix }}-private-subnet"
  register: private_subnet_result

# - name: Create nat gateway and allocate EIP
#   ec2_vpc_nat_gateway:
#     state: present
#     subnet_id: "{{ public_subnet_result.subnet.id }}"
#     wait: yes
#     region: "{{ aws_region }}"
#     if_exist_do_not_create: true
#   register: nat_gateway_result
#
#
# - name: Terminate nat gateway and wait for deleted status.
#   ec2_vpc_nat_gateway:
#     state: absent
#     nat_gateway_id: "{{ nat_gateway_result.nat_gateway_id }}"
#     wait: yes
#     wait_timeout: 300
#     release_eip: yes
#     region: "{{ aws_region }}"

- name: Terminate EC2 VPC Internet Gateway
  ec2_vpc_igw:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ aws_region }}"
    state: absent


- name: Terminate EC2 VPC Private Subnet within CIDR block
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ aws_region }}"
    state: absent
    cidr: "{{ aws_private_subnet_cidr_block }}"

- name: Terminate EC2 VPC Public Subnet within CIDR block
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ aws_region }}"
    state: absent
    cidr: "{{ aws_public_subnet_cidr_block }}"

- name: Terminate EC2 VPC Public Subnet Route Table
  ec2_vpc_route_table:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ aws_region }}"
    state: absent
    tags:
      Name: "{{ moadsd_ng_prefix }}-public-rt"
  register: public_route_table

- name: Terminate EC2 VPC Public Subnet Route Table
  ec2_vpc_route_table:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ aws_region }}"
    state: absent
    tags:
      Name: "{{ moadsd_ng_prefix }}-private-rt"
  register: public_route_table

- name: Terminate VPC
  local_action:
    module: ec2_vpc_net
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: "{{ moadsd_ng_prefix }}-vpc"
    cidr_block: "{{ aws_vpc_cidr_block }}"
    region: "{{ aws_region }}"
    state: absent
