---
# #####################################################################
# Start an instance in AWS environment
# #####################################################################
- name: Current play
  debug:
    msg: "Starting instance {{ instance_id }}"

- name: Start instance
  delegate_to: 127.0.0.1
  command: aws ec2 start-instances --instance-ids "{{ instance_id }}" --region {{ aws_region }} 
