---
# #####################################################################
# Create a network in AWS environment
# #####################################################################
- name: Current play
  debug:
    msg:
      - "Creating network {{ moadsd_ng_prefix }}-vpc"

- name: Create an EC2 VPC
  ec2_vpc_net:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: "{{ moadsd_ng_prefix }}-vpc"
    cidr_block: "{{ aws_vpc_cidr_block }}"
    region: "{{ aws_region }}"
    dns_support: yes
    dns_hostnames: yes
    tenancy: default
    state: present
    tags:
      Name: "{{ moadsd_ng_prefix }}-igw"
      project: "{{ moadsd_ng_prefix }}"
      user: "{{ moadsd_ng_user }}"
  register: ec2_vpc_net_result

- name: Create EC2 VPC Internet Gateway
  ec2_vpc_igw:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ aws_region }}"
    state: present
    tags:
      Name: "{{ moadsd_ng_prefix }}-igw"
      project: "{{ moadsd_ng_prefix }}"
      user: "{{ moadsd_ng_user }}"
  register: igw_result

- name: Create EC2 VPC Public Subnet within CIDR block
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ aws_region }}"
    az: "{{ aws_zone }}"
    state: present
    cidr: "{{ aws_public_subnet_cidr_block }}"
    map_public: yes
    resource_tags:
      Name: "{{ moadsd_ng_prefix }}-public-subnet"
      project: "{{ moadsd_ng_prefix }}"
      user: "{{ moadsd_ng_user }}"
  register: public_subnet_result

- name: Create EC2 VPC Private Subnet within CIDR block
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ aws_region }}"
    az: "{{ aws_zone }}"
    state: present
    cidr: "{{ aws_private_subnet_cidr_block }}"
    map_public: yes
    resource_tags:
      Name: "{{ moadsd_ng_prefix }}-private-subnet"
      project: "{{ moadsd_ng_prefix }}"
      user: "{{ moadsd_ng_user }}"
  register: private_subnet_result

- name: Create NAT Gateway and allocate EIP
  ec2_vpc_nat_gateway:
    state: present
    subnet_id: "{{ public_subnet_result.subnet.id }}"
    wait: yes
    region: "{{ aws_region }}"
    if_exist_do_not_create: true
  register: nat_gateway_result

- name: Create EC2 VPC Public Subnet Route Table
  ec2_vpc_route_table:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ aws_region }}"
    state: present
    tags:
      Name: "{{ moadsd_ng_prefix }}-public-rt"
      project: "{{ moadsd_ng_prefix }}"
      user: "{{ moadsd_ng_user }}"
    subnets: [ "{{ public_subnet_result.subnet.id }}" ]
    routes:
      - dest: "0.0.0.0/0"
        gateway_id: "{{ igw_result.gateway_id }}"
  register: public_route_table

- name: Create EC2 VPC Private Subnet Route Table
  ec2_vpc_route_table:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ aws_region }}"
    state: present
    tags:
      Name: "{{ moadsd_ng_prefix }}-private-rt"
      project: "{{ moadsd_ng_prefix }}"
      user: "{{ moadsd_ng_user }}"
    subnets: [ "{{ private_subnet_result.subnet.id }}" ]
    routes:
      - dest: "0.0.0.0/0"
        gateway_id: "{{ nat_gateway_result.nat_gateway_id }}"
  register: public_route_table
