---
# #####################################################################
# Resume a instance in AWS environment
# #####################################################################
- name: Current play
  debug:
    msg:
      - "Resuming instance {{ moadsd_ng_prefix }}-{{ instance_name }}-instance"

- name: Resume a server instance
  ec2_instance:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ moadsd_ng_prefix }}-{{ instance_name }}-instance"
      "tag:project": "{{ moadsd_ng_prefix }}"
      "tag:user": "{{ moadsd_ng_user }}"
      instance-state-name: [ "running", "stopped" ]
    state: running
  register: instance_state
  async: 600
  poll: 0
