# #####################################################################
# Create, Manage and Terminate AWS environment
# #####################################################################
---
- name: Create network and firewall rules
  include: ec2_create_network.yml
  when: operation == 'create_network'

- name: Create linux instance
  include: ec2_create_linux_instance.yml
  when: operation == 'create_linux_instance'

- name: Create windows instance
  include: ec2_create_windows_instance.yml
  when: operation == 'create_windows_instance'

- name: Pause instance
  include: ec2_pause_instance.yml
  when: operation == 'pause_instance'

- name: Resume instance
  include: ec2_resume_instance.yml
  when: operation == 'resume_instance'
  
- name: Terminate instance
  include: ec2_terminate_instance.yml
  when: operation == 'terminate_instance'

- name: Terminate network
  include: ec2_terminate_network.yml
  when: operation == 'terminate_network'
