# #####################################################################
# Create, Manage and Terminate AWS environment
# #####################################################################
---
- name: Create network and firewall rules
  include: ec2_create_network.yml
  when: operation == 'create_network'

- name: Create linux instance
  include: ec2_create_linux_instance.yml
  when: operation == 'create_linux_instance'

- name: Create windows instance
  include: ec2_create_windows_instance.yml
  when: operation == 'create_windows_instance'

- name: Stop instance
  include: ec2_stop_instance.yml
  when: operation == 'stop_instance'

- name: Start instance
  include: ec2_start_instance.yml
  when: operation == 'start_instance'

- name: Terminate instance
  include: ec2_terminate_instance.yml
  when: operation == 'terminate_instance'

- name: Terminate network
  include: ec2_terminate_network.yml
  when: operation == 'terminate_network'
