# #####################################################################
# Create and Manage CodeReady Containers
# #####################################################################
---
- name: Deploy CodeReady Containers
  include: deploy.yml
  when: operation == 'deploy'
