# #####################################################################
# Create and Manage Jenkins
# #####################################################################
---
- name: Deploy
  include: deploy.yml
  when: operation == 'deploy'

- name: Create Credentials
  include: create_credentials.yml
  when: operation == 'create_credentials'

- name: Create Jenkins JNLP Slave Docker Image
  include: create_jnlp_slave.yml
  when: operation == 'create_slave'
