# #####################################################################
# Create, Manage and Terminate Deep Security Smart Check
# #####################################################################
---
- name: Create instance
  include: dssc_create_instance.yml
  when: operation == 'create_instance'

- name: Enable pre-registry scanning
  include: dssc_enable_pre_reg_scanning.yml
  when: operation == 'enable_pre_reg_scanning'

- name: Configure Smart Check
  include: dssc_configure.yml
  when: operation == 'configure'
