# #####################################################################
# Create and Manage Prometheus
# #####################################################################
---
- name: Deploy
  include: deploy.yml
  when: operation == 'deploy'
