# #####################################################################
# Create and Manage OPA
# #####################################################################
---
- name: Deploy
  include: deploy.yml
  when: operation == 'deploy'
