# #####################################################################
# Create and Manage OPA
# #####################################################################
---
- name: Deploy
  include: deploy.yml
  when: operation == 'deploy'

- name: Testcases
  include: testcases.yml
  when: operation == 'testcases'
